### PR TITLE
Add typescript definitions

### PR DESCRIPTION
**Pull request by Gusarich**
I don't see how raw JSON schemas would be useful. You still have to define all that stuff in your code in order to actually use it.
So I think instead of everybody writing new type definitions in their projects, we can just have it structured and maintained here.
It's still a draft, I'll add conditions soon.

I'm also going to properly check all of your original definitions for correctness and if I find anything missing or wrong I'll open a separate PR for that.

WORK IN PROGRESS:

- [x] Actions
- [x] Conditions
- [x] Events

### CODE REVIEW

**Comment by ixnoahlive** [comment]
Draft looks good, will approve once you've tinkered some more with it. let me know when it's good to go. I will keep the JSON Schemas as they may come in handy.

**Comment by Gusarich** [comment]
@NoahTheNerd what do you think about publishing this as NPM package once finished?

**Comment by ixnoahlive** [comment]
We may look into it! I like the idea. We will probably have it be a separate build as we want to include examples for implementations in things such as ChatTriggers Macros for ingame

**Comment by ixnoahlive** [comment]
Just updating you on the "ingame" task, they should all already match ingame and ones that don't were changed for consistency's sake or to be easier to scale & organise if similar actions are added. (e.g. some legacy actions were made in camelCase instead of the now standardized snake_case that actions use internally on Housing)

**Review by ixnoahlive — APPROVED** [review]
Looks good, I understand if you wish to polish more though I see no reason not to merge as it is right now and just tinker with it more later. We are still in a beta stage of this specification, after all.

**Comment by Gusarich** [comment]
> Looks good, I understand if you wish to polish more though I see no reason not to merge as it is right now and just tinker with it more later. We are still in a beta stage of this specification, after all.

@NoahTheNerd then it's ready to merge now I guess.

However, I'm still waiting for you to push the remaining event conditions to json.

Also I didn't really complete `HasItemCondition` type yet.

**Pull request merged**
